# Generated by Django 4.0.2 on 2022-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_evento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='num_inscritos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
