# Generated by Django 4.0.2 on 2022-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_evento_num_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='num_inscritos',
            field=models.IntegerField(verbose_name='Número de Inscritos'),
        ),
    ]
