# Generated by Django 4.0.2 on 2022-02-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_evento_num_inscritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='slug',
            field=models.SlugField(default='teste', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
