# Generated by Django 4.0.2 on 2022-02-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_materia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='slug',
        ),
        migrations.AlterField(
            model_name='materia',
            name='titulo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Título'),
        ),
    ]
