# Generated by Django 4.0.2 on 2022-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_aula_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='materia/', verbose_name='imagem'),
        ),
    ]
