# Generated by Django 4.0.2 on 2022-02-14 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_aula_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='materia/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='materia/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='materia/', verbose_name='imagem'),
        ),
    ]
