# Generated by Django 4.0.2 on 2022-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_curso_imagem_alter_evento_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/materia/', verbose_name='imagem'),
        ),
    ]
