# Generated by Django 4.0.2 on 2022-02-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_materia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='imagem',
            field=models.ImageField(upload_to='media/materia/', verbose_name='imagem'),
        ),
    ]
