# Generated by Django 4.0.2 on 2022-02-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_materia_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='num_inscritos',
        ),
    ]
